// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_aYOLkCwEmj4dAmcRaSrqVFAX4_MXcB4',
    appId: '1:757248177117:web:ffbcab0a2f444b181ffc34',
    messagingSenderId: '757248177117',
    projectId: 'swarm-fbced',
    authDomain: 'swarm-fbced.firebaseapp.com',
    storageBucket: 'swarm-fbced.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWoKB2Oyx5U-lHs2PyGX8x_ItkGstKYT0',
    appId: '1:757248177117:android:61b48abac59fa6941ffc34',
    messagingSenderId: '757248177117',
    projectId: 'swarm-fbced',
    storageBucket: 'swarm-fbced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtECRhaa7TZ5vmx7vAIPNr1vTfRZihhys',
    appId: '1:757248177117:ios:179c00d6a2671a271ffc34',
    messagingSenderId: '757248177117',
    projectId: 'swarm-fbced',
    storageBucket: 'swarm-fbced.appspot.com',
    iosClientId: '757248177117-mi4i6f18u951inptdq09a6eckkunu2ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtECRhaa7TZ5vmx7vAIPNr1vTfRZihhys',
    appId: '1:757248177117:ios:179c00d6a2671a271ffc34',
    messagingSenderId: '757248177117',
    projectId: 'swarm-fbced',
    storageBucket: 'swarm-fbced.appspot.com',
    iosClientId: '757248177117-mi4i6f18u951inptdq09a6eckkunu2ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
